package dev.mzcy.core.debug;

import net.kyori.adventure.text.minimessage.MiniMessage;
import net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer;
import org.bukkit.command.CommandSender;
import org.jetbrains.annotations.NotNull;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

/**
 * Renders the {@link DebugOverlay} output in two formats:
 *
 * <ul>
 *   <li><b>Chat</b>    — MiniMessage-formatted, sent directly to a {@link CommandSender}</li>
 *   <li><b>Plain</b>   — stripped of all formatting tags, suitable for paste upload</li>
 * </ul>
 *
 * <p>The plain renderer adds a header with timestamp, server version,
 * and Core version for easy identification of uploaded pastes.
 */
public final class DebugRenderer {

    private static final MiniMessage MINI = MiniMessage.miniMessage();
    private static final PlainTextComponentSerializer PLAIN =
            PlainTextComponentSerializer.plainText();
    private static final DateTimeFormatter DATE =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                    .withZone(ZoneOffset.UTC);

    private final DebugOverlay overlay;

    public DebugRenderer(@NotNull DebugOverlay overlay) {
        this.overlay = overlay;
    }

    // =========================================================================
    // Plain text rendering
    // =========================================================================

    /**
     * Renders the full debug output as a plain text string suitable
     * for uploading to a paste service.
     *
     * <p>Strips all MiniMessage formatting tags and prepends a metadata header.
     *
     * @param sender the command sender (used for metadata context)
     * @return the plain text debug report
     */
    @NotNull
    public String renderPlain(@NotNull CommandSender sender) {
        final StringBuilder sb = new StringBuilder();

        // Metadata header
        sb.append("=".repeat(50)).append("\n");
        sb.append("  Core Framework Debug Report\n");
        sb.append("=".repeat(50)).append("\n");
        sb.append("Generated : ").append(DATE.format(Instant.now())).append(" UTC\n");
        sb.append("Generated by : ").append(sender.getName()).append("\n");
        sb.append("=".repeat(50)).append("\n\n");

        // Render each section
        for (final DebugSection section : overlay.getRegistry().getSections()) {
            sb.append("[ ").append(section.getCategory()).append(" ]\n");

            for (final DebugEntry entry : section.getEntries()) {
                final String rawValue = entry.resolve();
                // Strip MiniMessage tags for plain output
                final String plainValue = stripMiniMessage(rawValue);

                if (plainValue.contains("\n")) {
                    sb.append("  ").append(entry.getLabel()).append(":\n");
                    for (final String line : plainValue.split("\n")) {
                        sb.append("    ").append(line).append("\n");
                    }
                } else {
                    sb.append("  ")
                            .append(padRight(entry.getLabel(), 28))
                            .append(": ")
                            .append(plainValue)
                            .append("\n");
                }
            }
            sb.append("\n");
        }

        sb.append("=".repeat(50)).append("\n");
        sb.append("Total entries : ")
                .append(overlay.getRegistry().totalEntries()).append("\n");
        sb.append("Total sections: ")
                .append(overlay.getRegistry().getSections().size()).append("\n");
        sb.append("=".repeat(50)).append("\n");

        return sb.toString();
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    @NotNull
    private String stripMiniMessage(@NotNull String input) {
        try {
            return PLAIN.serialize(MINI.deserialize(input));
        } catch (Exception ex) {
            // Fallback: regex strip
            return input.replaceAll("<[^>]+>", "");
        }
    }

    @NotNull
    private String padRight(@NotNull String text, int width) {
        if (text.length() >= width) return text;
        return text + " ".repeat(width - text.length());
    }
}