name: Core
version: '${version}'
main: dev.mzcy.core.CorePlugin
api-version: '1.21'
description: Core plugin framework
authors:
  - mzcy
website: https://mzcy.dev
load: STARTUP
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - FastAsyncWorldEdit